CREATE TABLE Test (
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [Char] CHAR NOT NULL,
    [NChar] CHAR NOT NULL,
    [Varchar] VARCHAR(255) NOT NULL,
    [NVarchar] NVARCHAR(255) NOT NULL,
    [Text] TEXT NOT NULL,
    [Bit] BIT NOT NULL,
    [TinyInt] TINYINT NOT NULL,
    [SmallInt] SMALLINT NOT NULL,
    [Int] INT NOT NULL,
    [BigInt] BIGINT NOT NULL,
    [Decimal] DECIMAl(10, 2) NOT NULL,
    [Numeric] NUMERIC NOT NULL,
    [Float] FLOAT NOT NULL,
    [DateTime] DATETIME NOT NULL,
    [Timestamp] TIMESTAMP NOT NULL,
    [Json] JSON NOT NULL,
    [Variant] SQL_VARIANT NULL,
)
