CREATE TABLE Post (
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [Title] NVARCHAR(255) NOT NULL,
    [Content] TEXT NOT NULL,
    [Status] NVARCHAR(50) NOT NULL,
    [CreatedAt] DATETIME NOT NULL,
);

CREATE TABLE User (
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [Username] NVARCHAR(255) NOT NULL UNIQUE,
    [Email] NVARCHAR(255) NOT NULL UNIQUE,
    [Password] NVARCHAR(255) NOT NULL,
    [RegisteredAt] DATETIME NOT NULL,
);

CREATE TABLE Comment (
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [Content] TEXT NOT NULL,
    [CreatedAt] DATETIME NOT NULL,
    [User] UNIQUEIDENTIFIER NOT NULL,
    [Post] UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (User) REFERENCES User(Id),
    FOREIGN KEY (Post) REFERENCES Post(Id),
);