CREATE TABLE Test (
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [Char] CHAR,
    [NChar] CHAR,
    [Varchar] VARCHAR(255),
    [NVarchar] NVARCHAR(255),
    [Text] TEXT,
    [Bit] BIT,
    [TinyInt] TINYINT,
    [SmallInt] SMALLINT,
    [Int] INT,
    [BigInt] BIGINT,
    [Decimal] DECIMAl(10, 2),
    [Numeric] NUMERIC,
    [Float] FLOAT,
    [DateTime] DATETIME,
    [Timestamp] TIMESTAMP,
    [Json] JSON,
    [Variant] SQL_VARIANT
)
