pub const ENV_SCHEMA: &str = "SURREAL_MIG_SCHEMA";
pub const ENV_SURREAL_ADDRESS: &str = "SURREAL_MIG_ADDRESS";
pub const ENV_SURREAL_USER: &str = "SURREAL_MIG_USER";
pub const ENV_SURREAL_PASS: &str = "SURREAL_MIG_PASS";
pub const ENV_SURREAL_NS: &str = "SURREAL_MIG_NS";
pub const ENV_SURREAL_DB: &str = "SURREAL_MIG_DB";
