name: Build Workflow

on:
  pull_request:
    branches:
      - "main"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Download SurrealDB
        run: curl -sSf https://install.surrealdb.com | sh
      - name: Run tests
        run: cargo test --verbose
