name: Samples Workflow

on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - "tests/**"
      - ".vscode/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build WASM example
        run: (cd samples/wasm/rsw-hello && wasm-pack build --target web)
